import React, { useState, useEffect } from 'react';
import { BookOpen, Award, FileText, Download, Sparkles, AlertCircle, Compass } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import MarkdownRenderer from './MarkdownRenderer';

interface BoardResourcesViewProps {
  onShowToast?: (message: string, type?: 'success' | 'warning' | 'info') => void;
}

export default function BoardResourcesView({ onShowToast }: BoardResourcesViewProps) {
  const { profile } = useAuth();
  const [loading, setLoading] = useState(true);
  const [boardData, setBoardData] = useState<any>(null);
  
  useEffect(() => {
    let mounted = true;
    const fetchBoardData = async () => {
      setLoading(true);
      try {
        // Create static content to avoid unnecessary Gemini API calls
        const targetBoard = profile?.board || 'CBSE';
        const targetClass = profile?.classLevel || '10';
        const targetMedium = profile?.medium || 'English Medium';
        
        let subjects = '';
        if (parseInt(targetClass) <= 8) {
           subjects = "Mathematics, Science, English, Social Science, Language II";
        } else if (parseInt(targetClass) <= 10) {
           subjects = "Mathematics, Science, English, Social Science, Hindi/Local Language";
        } else {
           subjects = "Physics, Chemistry, Mathematics/Biology, English, Optional (CS/PE)";
        }

        const staticMarkdown = `# ${targetBoard} - Class ${targetClass} (${targetMedium})

## 1. Board Overview
The ${targetBoard} syllabus is designed to provide holistic education while focusing on core academic and practical skills. It follows standard curriculum guidelines for Class ${targetClass} students.

## 2. Key Subjects
**Core Subjects:** ${subjects}

## 3. Exam Pattern Summary
* **Formative/Internal Assessments:** ~20% weightage. Continuous evaluation via unit tests, practicals, and projects.
* **Summative/Board Exams:** ~80% weightage. Final written examinations covering the entire year's syllabus.

## 4. Important Tips
* **Consistency:** Review notes daily.
* **Practice:** Solve previous year question papers regularly.
* **Clarity:** Focus on understanding concepts rather than rote learning.
* **Time Management:** Plan a strict revision schedule at least 2 months before exams.`;
        
        if (mounted) {
           // Simulate slight network delay for UI smoothness
           setTimeout(() => {
             if (mounted) setBoardData(staticMarkdown);
             if (mounted) setLoading(false);
           }, 500);
        }
      } catch (err: any) {
        if (mounted) {
          setBoardData(`**Error loading ${profile?.board} Class ${profile?.classLevel} information.**\nPlease check your settings and try again.\n\n` + err?.message);
          setLoading(false);
        }
      }
    };
    
    fetchBoardData();
    return () => { mounted = false; };
  }, [profile?.board, profile?.classLevel, profile?.medium]);

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-20 pt-2 animate-in fade-in">
      {/* Header */}
      <div className="bg-gradient-to-br from-blue-900 to-indigo-900 p-8 rounded-3xl text-white shadow-xl relative overflow-hidden">
        <div className="absolute right-0 top-0 w-64 h-64 bg-blue-500/20 rounded-full blur-[80px] pointer-events-none" />
        <div className="relative z-10">
          <div className="inline-flex items-center gap-1.5 bg-blue-500/20 border border-blue-500/30 px-3 py-1.5 rounded-xl text-[10px] uppercase font-bold tracking-widest text-blue-300 mb-3">
             <Compass className="w-3.5 h-3.5" />
             <span>Board Resources</span>
          </div>
          <h2 className="text-3xl md:text-5xl font-black leading-tight tracking-tight text-white mb-2">
            {profile?.board || 'Standard'} Board
          </h2>
          <p className="text-[17px] text-blue-200/80 font-medium leading-relaxed">
            Class {profile?.classLevel || '10'} Syllabus & Study Materials
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
         {/* Main Content Area */}
         <div className="md:col-span-2 space-y-6">
            <div className="bg-[#131825] rounded-3xl p-6 md:p-8 border border-gray-800 shadow-xl min-h-[400px]">
               <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2 border-b border-gray-800 pb-4">
                 <Sparkles className="w-5 h-5 text-indigo-400" />
                 Syllabus Overview generated by AI
               </h3>
               
               {loading ? (
                 <div className="flex flex-col items-center justify-center h-48 opacity-50 space-y-4">
                    <div className="w-8 h-8 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
                    <span className="text-sm font-medium text-gray-400">Loading {profile?.board} details...</span>
                 </div>
               ) : (
                 <div className="prose prose-sm dark:prose-invert max-w-none text-gray-300">
                    <MarkdownRenderer content={boardData || ''} />
                 </div>
               )}
            </div>
         </div>

         {/* Sidebar Actions */}
         <div className="space-y-4">
            <div className="bg-[#1A2235] rounded-2xl p-5 border border-gray-800">
              <h4 className="text-[11px] font-black uppercase text-gray-500 tracking-widest block mb-4">Quick Links</h4>
              
              <div className="space-y-2">
                 <button className="w-full flex items-center gap-3 p-3 bg-[#131825] hover:bg-white/5 border border-gray-800 rounded-xl transition-colors cursor-pointer text-left group">
                    <div className="w-8 h-8 rounded-lg bg-indigo-500/10 flex items-center justify-center shrink-0">
                       <FileText className="w-4 h-4 text-indigo-400 group-hover:text-indigo-300" />
                    </div>
                    <div className="flex-1">
                      <span className="text-sm font-bold text-white block">Syllabus PDF</span>
                      <span className="text-[10px] text-gray-500">View official topics</span>
                    </div>
                    <Download className="w-4 h-4 text-gray-500" />
                 </button>

                 <button className="w-full flex items-center gap-3 p-3 bg-[#131825] hover:bg-white/5 border border-gray-800 rounded-xl transition-colors cursor-pointer text-left group">
                    <div className="w-8 h-8 rounded-lg bg-emerald-500/10 flex items-center justify-center shrink-0">
                       <Award className="w-4 h-4 text-emerald-400 group-hover:text-emerald-300" />
                    </div>
                    <div className="flex-1">
                      <span className="text-sm font-bold text-white block">Past Papers</span>
                      <span className="text-[10px] text-gray-500">Previous year questions</span>
                    </div>
                    <Download className="w-4 h-4 text-gray-500" />
                 </button>

                 <button className="w-full flex items-center gap-3 p-3 bg-[#131825] hover:bg-white/5 border border-gray-800 rounded-xl transition-colors cursor-pointer text-left group">
                    <div className="w-8 h-8 rounded-lg bg-amber-500/10 flex items-center justify-center shrink-0">
                       <BookOpen className="w-4 h-4 text-amber-400 group-hover:text-amber-300" />
                    </div>
                    <div className="flex-1">
                      <span className="text-sm font-bold text-white block">Textbooks</span>
                      <span className="text-[10px] text-gray-500">Authorized materials</span>
                    </div>
                    <Download className="w-4 h-4 text-gray-500" />
                 </button>
              </div>
            </div>

            <div className="bg-gradient-to-br from-[#131825] to-[#1A2235] rounded-2xl p-5 border border-gray-800 flex items-start gap-3">
               <AlertCircle className="w-5 h-5 text-indigo-400 shrink-0" />
               <p className="text-xs text-gray-400 leading-relaxed">
                 The syllabus information is powered by AI. For official and updated curriculum, please refer to the official <strong className="text-gray-200">{profile?.board}</strong> website.
               </p>
            </div>
         </div>
      </div>
    </div>
  );
}
