import React, { useState, useEffect } from 'react';
import { BookOpen, Award, FileText, Download, Sparkles, AlertCircle, Compass } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import MarkdownRenderer from './MarkdownRenderer';

interface BoardResourcesViewProps {
  onShowToast?: (message: string, type?: 'success' | 'warning' | 'info') => void;
}

export default function BoardResourcesView({ onShowToast }: BoardResourcesViewProps) {
  const { profile } = useAuth();
  const [loading, setLoading] = useState(true);
  const [boardData, setBoardData] = useState<any>(null);
  
  useEffect(() => {
    let mounted = true;
    const fetchBoardData = async () => {
      setLoading(true);
      try {
        const res = await fetch('/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
             question: `Generate a brief study overview and syllabus summary for ${profile?.board || 'CBSE'} Class ${profile?.classLevel || '10'} students. Create it using Markdown. Structure: 1. Board Overview. 2. Key Subjects. 3. Exam Pattern summary. 4. Important Tips. Keep it under 300 words.`,
             subject: 'Board Information',
             board: profile?.board,
             classLevel: profile?.classLevel,
             medium: profile?.medium
          })
        });
        
        if (!res.ok) {
           const contentType = res.headers.get("content-type");
           if (contentType && contentType.includes("application/json")) {
             const errData = await res.json();
             throw new Error(errData.error || "Failed to load");
           }
           throw new Error("Failed to load");
        }
        let data;
        try {
           data = await res.json();
        } catch (parseErr) {
           throw new Error("Received an invalid response from the server. Please try again.");
        }
        
        if (mounted) {
           setBoardData(data.answer);
        }
      } catch (err: any) {
        if (mounted) {
          setBoardData(`**Error loading ${profile?.board} Class ${profile?.classLevel} information.**\nPlease check your Gemini API key and try again.\n\n` + err?.message);
        }
      } finally {
        if (mounted) setLoading(false);
      }
    };
    
    fetchBoardData();
    return () => { mounted = false; };
  }, [profile?.board, profile?.classLevel]);

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-20 pt-2 animate-in fade-in">
      {/* Header */}
      <div className="bg-gradient-to-br from-blue-900 to-indigo-900 p-8 rounded-3xl text-white shadow-xl relative overflow-hidden">
        <div className="absolute right-0 top-0 w-64 h-64 bg-blue-500/20 rounded-full blur-[80px] pointer-events-none" />
        <div className="relative z-10">
          <div className="inline-flex items-center gap-1.5 bg-blue-500/20 border border-blue-500/30 px-3 py-1.5 rounded-xl text-[10px] uppercase font-bold tracking-widest text-blue-300 mb-3">
             <Compass className="w-3.5 h-3.5" />
             <span>Board Resources</span>
          </div>
          <h2 className="text-3xl md:text-5xl font-black leading-tight tracking-tight text-white mb-2">
            {profile?.board || 'Standard'} Board
          </h2>
          <p className="text-[17px] text-blue-200/80 font-medium leading-relaxed">
            Class {profile?.classLevel || '10'} Syllabus & Study Materials
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
         {/* Main Content Area */}
         <div className="md:col-span-2 space-y-6">
            <div className="bg-[#131825] rounded-3xl p-6 md:p-8 border border-gray-800 shadow-xl min-h-[400px]">
               <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2 border-b border-gray-800 pb-4">
                 <Sparkles className="w-5 h-5 text-indigo-400" />
                 Syllabus Overview generated by AI
               </h3>
               
               {loading ? (
                 <div className="flex flex-col items-center justify-center h-48 opacity-50 space-y-4">
                    <div className="w-8 h-8 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
                    <span className="text-sm font-medium text-gray-400">Loading {profile?.board} details...</span>
                 </div>
               ) : (
                 <div className="prose prose-sm dark:prose-invert max-w-none text-gray-300">
                    <MarkdownRenderer content={boardData || ''} />
                 </div>
               )}
            </div>
         </div>

         {/* Sidebar Actions */}
         <div className="space-y-4">
            <div className="bg-[#1A2235] rounded-2xl p-5 border border-gray-800">
              <h4 className="text-[11px] font-black uppercase text-gray-500 tracking-widest block mb-4">Quick Links</h4>
              
              <div className="space-y-2">
                 <button className="w-full flex items-center gap-3 p-3 bg-[#131825] hover:bg-white/5 border border-gray-800 rounded-xl transition-colors cursor-pointer text-left group">
                    <div className="w-8 h-8 rounded-lg bg-indigo-500/10 flex items-center justify-center shrink-0">
                       <FileText className="w-4 h-4 text-indigo-400 group-hover:text-indigo-300" />
                    </div>
                    <div className="flex-1">
                      <span className="text-sm font-bold text-white block">Syllabus PDF</span>
                      <span className="text-[10px] text-gray-500">View official topics</span>
                    </div>
                    <Download className="w-4 h-4 text-gray-500" />
                 </button>

                 <button className="w-full flex items-center gap-3 p-3 bg-[#131825] hover:bg-white/5 border border-gray-800 rounded-xl transition-colors cursor-pointer text-left group">
                    <div className="w-8 h-8 rounded-lg bg-emerald-500/10 flex items-center justify-center shrink-0">
                       <Award className="w-4 h-4 text-emerald-400 group-hover:text-emerald-300" />
                    </div>
                    <div className="flex-1">
                      <span className="text-sm font-bold text-white block">Past Papers</span>
                      <span className="text-[10px] text-gray-500">Previous year questions</span>
                    </div>
                    <Download className="w-4 h-4 text-gray-500" />
                 </button>

                 <button className="w-full flex items-center gap-3 p-3 bg-[#131825] hover:bg-white/5 border border-gray-800 rounded-xl transition-colors cursor-pointer text-left group">
                    <div className="w-8 h-8 rounded-lg bg-amber-500/10 flex items-center justify-center shrink-0">
                       <BookOpen className="w-4 h-4 text-amber-400 group-hover:text-amber-300" />
                    </div>
                    <div className="flex-1">
                      <span className="text-sm font-bold text-white block">Textbooks</span>
                      <span className="text-[10px] text-gray-500">Authorized materials</span>
                    </div>
                    <Download className="w-4 h-4 text-gray-500" />
                 </button>
              </div>
            </div>

            <div className="bg-gradient-to-br from-[#131825] to-[#1A2235] rounded-2xl p-5 border border-gray-800 flex items-start gap-3">
               <AlertCircle className="w-5 h-5 text-indigo-400 shrink-0" />
               <p className="text-xs text-gray-400 leading-relaxed">
                 The syllabus information is powered by AI. For official and updated curriculum, please refer to the official <strong className="text-gray-200">{profile?.board}</strong> website.
               </p>
            </div>
         </div>
      </div>
    </div>
  );
}
