export const localFormulas = [
  // ================= Math: Basic & Mensuration (Classes 6-8) =================
  {
    id: "m_basic_01",
    title: "Area of a Rectangle",
    formula: "A = l \\times w",
    category: "Mensuration",
    subject: "Mathematics",
    chapter: "Mensuration",
    description: "Calculates the area enclosed by a rectangle.",
    variables: [{ symbol: "l", meaning: "Length", unit: "m" }, { symbol: "w", meaning: "Width", unit: "m" }, { symbol: "A", meaning: "Area", unit: "m^2" }],
    targetClasses: [6, 7, 8],
    importanceTags: ["📘 NCERT Essential"],
    exampleProblem: { scenario: "Find area if length is 5m and width is 3m", calc: "5 * 3", answer: "15 m^2" },
    commonMistakes: "Forgetting to ensure both length and width are in the same units.",
    examTip: "Always write the final unit as a square unit (e.g., cm^2, m^2).",
  },
  {
    id: "m_basic_02",
    title: "Area of a Circle",
    formula: "A = \\pi r^2",
    category: "Mensuration",
    subject: "Mathematics",
    chapter: "Mensuration",
    description: "Calculates the area enclosed by a circle of radius r.",
    variables: [{ symbol: "r", meaning: "Radius", unit: "m" }, { symbol: "A", meaning: "Area", unit: "m^2" }],
    targetClasses: [7, 8, 9, 10],
    importanceTags: ["🔥 Most Important", "⭐ Frequently Asked"],
    exampleProblem: { scenario: "Find area if radius is 7 cm", calc: "π * 7²", answer: "153.94 cm²" },
    commonMistakes: "Using diameter instead of radius in the formula.",
    examTip: "Use π = 22/7 for calculations if the radius is a multiple of 7.",
  },
  {
    id: "m_basic_perim_rect",
    title: "Perimeter of a Rectangle",
    formula: "P = 2(l + w)",
    category: "Mensuration",
    subject: "Mathematics",
    chapter: "Mensuration",
    description: "Calculates the total boundary length of a rectangle.",
    variables: [{ symbol: "l", meaning: "Length", unit: "m" }, { symbol: "w", meaning: "Width", unit: "m" }, { symbol: "P", meaning: "Perimeter", unit: "m" }],
    targetClasses: [6, 7, 8],
    importanceTags: ["📘 NCERT Essential"],
  },
  {
    id: "m_basic_circum_circle",
    title: "Circumference of a Circle",
    formula: "C = 2\\pi r",
    category: "Mensuration",
    subject: "Mathematics",
    chapter: "Mensuration",
    description: "Calculates the total boundary length of a circle.",
    variables: [{ symbol: "r", meaning: "Radius", unit: "m" }, { symbol: "C", meaning: "Circumference", unit: "m" }],
    targetClasses: [7, 8, 9, 10],
    importanceTags: ["📘 NCERT Essential"],
  },
  {
    id: "m_basic_vol_cylinder",
    title: "Volume of a Cylinder",
    formula: "V = \\pi r^2 h",
    category: "Mensuration",
    subject: "Mathematics",
    chapter: "Surface Areas and Volumes",
    description: "Calculates the volume of a right circular cylinder.",
    variables: [{ symbol: "r", meaning: "Radius of base", unit: "m" }, { symbol: "h", meaning: "Height", unit: "m" }, { symbol: "V", meaning: "Volume", unit: "m^3" }],
    targetClasses: [8, 9, 10],
    importanceTags: ["🔥 Most Important", "🎯 Board Exam Focused"],
    examTip: "Check that radius and height share the same unit.",
  },
  {
    id: "m_basic_surf_cylinder",
    title: "Curved Surface Area of a Cylinder",
    formula: "CSA = 2\\pi rh",
    category: "Mensuration",
    subject: "Mathematics",
    chapter: "Surface Areas and Volumes",
    description: "Calculates the curved surface area of a cylinder.",
    variables: [{ symbol: "r", meaning: "Radius formatting", unit: "m" }, { symbol: "h", meaning: "Height", unit: "m" }, { symbol: "CSA", meaning: "Curved Surface Area", unit: "m^2" }],
    targetClasses: [8, 9, 10],
    importanceTags: ["⭐ Frequently Asked"],
  },
  {
    id: "m_basic_03",
    title: "Simple Interest",
    formula: "SI = \\frac{P \\times R \\times T}{100}",
    category: "Percentages",
    subject: "Mathematics",
    chapter: "Comparing Quantities",
    description: "Calculates the simple interest on a principal amount over time.",
    variables: [{ symbol: "P", meaning: "Principal", unit: "₹" }, { symbol: "R", meaning: "Rate of Interest", unit: "%" }, { symbol: "T", meaning: "Time", unit: "Years" }],
    targetClasses: [7, 8],
    importanceTags: ["📘 NCERT Essential"],
    exampleProblem: { scenario: "Find SI for ₹1000 at 5% for 2 years", calc: "(1000 * 5 * 2) / 100", answer: "₹100" },
    commonMistakes: "Using time in months instead of years.",
  },
  
  // ================= Math: Quadratic Equations (Classes 9-10) =================
  {
    id: "m_alg_quad_01",
    title: "Quadratic Formula",
    formula: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    category: "Algebra",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    description: "Used to find the roots of a quadratic equation ax² + bx + c = 0.",
    variables: [{ symbol: "a", meaning: "x^2 coefficient" }, { symbol: "b", meaning: "x coefficient" }, { symbol: "c", meaning: "Constant term" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["🔥 Most Important", "🎯 Board Exam Focused"],
    commonMistakes: "Forgetting the ± sign, which leads to missing one root.",
  },
  {
    id: "m_alg_quad_02",
    title: "Discriminant Formula",
    formula: "D = b^2 - 4ac",
    category: "Algebra",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    description: "Determines the nature of roots for a quadratic equation.",
    variables: [{ symbol: "a, b, c", meaning: "Coefficients of the quadratic equation" }, { symbol: "D", meaning: "Discriminant" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["⭐ Frequently Asked"],
    examTip: "If D > 0, roots are real and distinct. If D = 0, roots are real and equal. If D < 0, roots are imaginary.",
  },
  {
    id: "m_alg_quad_03",
    title: "Sum of Roots",
    formula: "\\alpha + \\beta = -\\frac{b}{a}",
    category: "Algebra",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    description: "Relationship between the sum of roots and coefficients.",
    variables: [{ symbol: "\\alpha, \\beta", meaning: "Roots of equation" }, { symbol: "a, b", meaning: "Coefficients" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["📘 NCERT Essential"],
  },
  {
    id: "m_alg_quad_04",
    title: "Product of Roots",
    formula: "\\alpha \\beta = \\frac{c}{a}",
    category: "Algebra",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    description: "Relationship between the product of roots and coefficients.",
    variables: [{ symbol: "\\alpha, \\beta", meaning: "Roots of equation" }, { symbol: "a, c", meaning: "Coefficients" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["📘 NCERT Essential"],
  },
  {
    id: "m_alg_quad_05",
    title: "Formation of Quadratic Equation",
    formula: "x^2 - (\\alpha + \\beta)x + (\\alpha \\beta) = 0",
    category: "Algebra",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    description: "Forming a quadratic equation when roots are given.",
    variables: [{ symbol: "\\alpha, \\beta", meaning: "Roots" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["⭐ Frequently Asked"],
  },

  // ================= Math: Coordinate Geometry (Classes 9-10) =================
  {
    id: "m_geom_01",
    title: "Distance Formula",
    formula: "d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}",
    category: "Coordinate Geometry",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    description: "Calculates the distance between two points (x1, y1) and (x2, y2).",
    variables: [{ symbol: "x_1, y_1", meaning: "First point coordinates" }, { symbol: "x_2, y_2", meaning: "Second point coordinates" }],
    targetClasses: [9, 10, 11],
    importanceTags: ["📘 NCERT Essential", "🔥 Most Important"],
    commonMistakes: "Mixing up x and y coordinates during subtraction.",
  },
  {
    id: "m_geom_02",
    title: "Section Formula",
    formula: "P(x,y) = \\left( \\frac{m_1 x_2 + m_2 x_1}{m_1 + m_2}, \\frac{m_1 y_2 + m_2 y_1}{m_1 + m_2} \\right)",
    category: "Coordinate Geometry",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    description: "Finds the coordinates of a point dividing a line segment in ratio m1:m2.",
    variables: [{ symbol: "m_1, m_2", meaning: "Ratio" }],
    targetClasses: [10, 11],
    importanceTags: ["🎯 Board Exam Focused"],
  },
  {
    id: "m_geom_03",
    title: "Midpoint Formula",
    formula: "M(x,y) = \\left( \\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2} \\right)",
    category: "Coordinate Geometry",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    description: "Finds the midpoint of a line segment.",
    variables: [{ symbol: "x_1, y_1", meaning: "First point coordinates" }, { symbol: "x_2, y_2", meaning: "Second point coordinates" }],
    targetClasses: [9, 10, 11],
    importanceTags: ["📘 NCERT Essential"],
  },
  {
    id: "m_geom_04",
    title: "Area of a Triangle (Coordinate Geometry)",
    formula: "A = \\frac{1}{2} \\left| x_1(y_2 - y_3) + x_2(y_3 - y_1) + x_3(y_1 - y_2) \\right|",
    category: "Coordinate Geometry",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    description: "Area of a triangle formed by three points.",
    variables: [{ symbol: "x_i, y_i", meaning: "Coordinates of vertices" }],
    targetClasses: [10, 11],
    importanceTags: ["⭐ Frequently Asked"],
    examTip: "Keep the cyclic order 1→2→3 to avoid sign errors.",
  },

  // ================= Math: Trigonometry (Classes 10-12) =================
  {
    id: "m_trig_ratios",
    title: "Basic Trigonometric Ratios",
    formula: "\\sin \\theta = \\frac{P}{H}, \\quad \\cos \\theta = \\frac{B}{H}, \\quad \\tan \\theta = \\frac{P}{B}",
    category: "Trigonometry",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    description: "Fundamental ratios in a right-angled triangle.",
    variables: [{ symbol: "P", meaning: "Perpendicular" }, { symbol: "B", meaning: "Base" }, { symbol: "H", meaning: "Hypotenuse" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["🔥 Most Important"],
  },
  {
    id: "m_trig_recip",
    title: "Reciprocal Identities",
    formula: "\\csc \\theta = \\frac{1}{\\sin \\theta}, \\quad \\sec \\theta = \\frac{1}{\\cos \\theta}, \\quad \\cot \\theta = \\frac{1}{\\tan \\theta}",
    category: "Trigonometry",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    description: "Reciprocal relationships between trig ratios.",
    variables: [{ symbol: "\\theta", meaning: "Angle" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["📘 NCERT Essential"],
  },
  {
    id: "m_trig_01",
    title: "Pythagorean Identity",
    formula: "\\sin^2\\theta + \\cos^2\\theta = 1",
    category: "Trigonometry",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    description: "The fundamental relation between the sine and cosine of an angle.",
    variables: [{ symbol: "\\theta", meaning: "Angle", unit: "Degrees/Radians" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["🔥 Most Important", "⭐ Frequently Asked"],
    commonMistakes: "Writing sin(θ²) instead of sin²(θ).",
  },
  {
    id: "m_trig_02",
    title: "Pythagorean Identity 2",
    formula: "1 + \\tan^2\\theta = \\sec^2\\theta",
    category: "Trigonometry",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    description: "Relation between tangent and secant.",
    variables: [{ symbol: "\\theta", meaning: "Angle" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["⭐ Frequently Asked"],
  },
  {
    id: "m_trig_03",
    title: "Pythagorean Identity 3",
    formula: "1 + \\cot^2\\theta = \\csc^2\\theta",
    category: "Trigonometry",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    description: "Relation between cotangent and cosecant.",
    variables: [{ symbol: "\\theta", meaning: "Angle" }],
    targetClasses: [10, 11, 12],
    importanceTags: ["📘 NCERT Essential"],
  },
  {
    id: "m_stat_01",
    title: "Mean of Grouped Data (Direct Method)",
    formula: "\\bar{x} = \\frac{\\sum f_i x_i}{\\sum f_i}",
    category: "Statistics",
    subject: "Mathematics",
    chapter: "Statistics",
    description: "Calculates the mean of grouped data where f_i is frequency and x_i is class mark.",
    variables: [{ symbol: "f_i", meaning: "Frequency" }, { symbol: "x_i", meaning: "Class Mark" }],
    targetClasses: [10, 11],
    importanceTags: ["🎯 Board Exam Focused"],
    commonMistakes: "Calculating x_i incorrectly; it must be (Upper Limit + Lower Limit) / 2.",
  },

  // ================= Math: Advanced (Classes 11-12) =================
  {
    id: "m_calc_01",
    title: "Derivative of Power Rule",
    formula: "\\frac{d}{dx}(x^n) = nx^{n-1}",
    category: "Calculus",
    subject: "Mathematics",
    chapter: "Derivatives",
    description: "The basic rule for differentiating a variable raised to a power.",
    variables: [{ symbol: "n", meaning: "Exponent" }, { symbol: "x", meaning: "Variable" }],
    targetClasses: [11, 12],
    importanceTags: ["🔥 Most Important"],
    commonMistakes: "Forgetting to subtract 1 from the exponent after multiplying.",
  },
  {
    id: "m_calc_02",
    title: "Integration by Parts",
    formula: "\\int u \\, dv = uv - \\int v \\, du",
    category: "Calculus",
    subject: "Mathematics",
    chapter: "Integrals",
    description: "A method to integrate the product of two functions.",
    variables: [{ symbol: "u, v", meaning: "Functions of x" }],
    targetClasses: [12],
    importanceTags: ["⭐ Frequently Asked", "🎯 Board Exam Focused"],
    examTip: "ILATE rule: Inverse Trig, Logarithmic, Algebraic, Trigonometric, Exponential.",
  },

  // ================= Physics (Classes 9-12) =================
  {
    id: "p_mot_01",
    title: "Newton's Second Law",
    formula: "F = ma",
    category: "Laws of Motion",
    subject: "Physics",
    chapter: "Laws of Motion",
    description: "The net force acting on an object is equal to its mass times its acceleration.",
    variables: [{ symbol: "F", meaning: "Force", unit: "N" }, { symbol: "m", meaning: "Mass", unit: "kg" }, { symbol: "a", meaning: "Acceleration", unit: "m/s^2" }],
    targetClasses: [9, 11],
    importanceTags: ["🔥 Most Important", "📘 NCERT Essential"],
    examTip: "F in this equation represents the NET force. Always resolve force vectors first.",
  },
  {
    id: "p_mot_02",
    title: "First Equation of Motion",
    formula: "v = u + at",
    category: "Kinematics",
    subject: "Physics",
    chapter: "Motion",
    description: "Relates final velocity to initial velocity, constant acceleration, and time.",
    variables: [{ symbol: "v", meaning: "Final Velocity", unit: "m/s" }, { symbol: "u", meaning: "Initial Velocity", unit: "m/s" }, { symbol: "a", meaning: "Acceleration", unit: "m/s^2" }, { symbol: "t", meaning: "Time", unit: "s" }],
    targetClasses: [9, 11],
    importanceTags: ["⭐ Frequently Asked"],
    commonMistakes: "Forgetting sign conventions for upward/downward motion under gravity.",
  },
  {
    id: "p_mot_03",
    title: "Second Equation of Motion",
    formula: "s = ut + \\frac{1}{2}at^2",
    category: "Kinematics",
    subject: "Physics",
    chapter: "Motion",
    description: "Relates displacement to initial velocity, acceleration and time.",
    variables: [{ symbol: "s", meaning: "Displacement", unit: "m" }, { symbol: "u", meaning: "Initial Velocity", unit: "m/s" }, { symbol: "t", meaning: "Time", unit: "s" }, { symbol: "a", meaning: "Acceleration", unit: "m/s^2" }],
    targetClasses: [9, 11],
    importanceTags: ["🎯 Board Exam Focused", "🔥 Most Important"],
  },
  {
    id: "p_mot_04",
    title: "Third Equation of Motion",
    formula: "v^2 = u^2 + 2as",
    category: "Kinematics",
    subject: "Physics",
    chapter: "Motion",
    description: "Relates final velocity, initial velocity, acceleration, and displacement.",
    variables: [{ symbol: "v", meaning: "Final Velocity", unit: "m/s" }, { symbol: "u", meaning: "Initial Velocity", unit: "m/s" }, { symbol: "a", meaning: "Acceleration", unit: "m/s^2" }, { symbol: "s", meaning: "Displacement", unit: "m" }],
    targetClasses: [9, 11],
    importanceTags: ["⭐ Frequently Asked"],
  },
  {
    id: "p_thermo_01",
    title: "Ideal Gas Law",
    formula: "PV = nRT",
    category: "Thermodynamics",
    subject: "Physics",
    chapter: "Thermodynamics",
    description: "The equation of state of a hypothetical ideal gas.",
    variables: [{ symbol: "P", meaning: "Pressure", unit: "Pa" }, { symbol: "V", meaning: "Volume", unit: "m^3" }, { symbol: "n", meaning: "Number of moles", unit: "mol" }, { symbol: "R", meaning: "Ideal Gas Constant", unit: "J/(mol K)" }, { symbol: "T", meaning: "Temperature", unit: "K" }],
    targetClasses: [11],
    importanceTags: ["🔥 Most Important"],
    commonMistakes: "Using temperature in Celsius instead of Kelvin.",
  },
  {
    id: "p_elec_01",
    title: "Ohm's Law",
    formula: "V = IR",
    category: "Electricity",
    subject: "Physics",
    chapter: "Electricity",
    description: "Voltage across a conductor is proportional to the current flowing through it.",
    variables: [{ symbol: "V", meaning: "Voltage/Potential Difference", unit: "V" }, { symbol: "I", meaning: "Current", unit: "A" }, { symbol: "R", meaning: "Resistance", unit: "\\Omega" }],
    targetClasses: [10, 12],
    importanceTags: ["🔥 Most Important", "🎯 Board Exam Focused"],
    examTip: "Remember that Ohm's law only holds true if physical conditions like temperature remain constant.",
  },
  {
    id: "p_elec_02",
    title: "Power (Electricity)",
    formula: "P = VI = I^2R = \\frac{V^2}{R}",
    category: "Electricity",
    subject: "Physics",
    chapter: "Electricity",
    description: "Electric power calculation in a circuit.",
    variables: [{ symbol: "P", meaning: "Power", unit: "W" }, { symbol: "V", meaning: "Voltage", unit: "V" }, { symbol: "I", meaning: "Current", unit: "A" }, { symbol: "R", meaning: "Resistance", unit: "\\Omega" }],
    targetClasses: [10, 12],
    importanceTags: ["⭐ Frequently Asked"],
  },
  {
    id: "p_optics_01",
    title: "Lens Formula",
    formula: "\\frac{1}{f} = \\frac{1}{v} - \\frac{1}{u}",
    category: "Optics",
    subject: "Physics",
    chapter: "Light - Reflection and Refraction",
    description: "Relates the focal length, image distance, and object distance of a spherical lens.",
    variables: [{ symbol: "f", meaning: "Focal Length", unit: "m" }, { symbol: "v", meaning: "Image Distance", unit: "m" }, { symbol: "u", meaning: "Object Distance", unit: "m" }],
    targetClasses: [10, 12],
    importanceTags: ["🎯 Board Exam Focused"],
    commonMistakes: "Incorrect sign convention (u is always negative).",
    examTip: "Always double-check Cartesian sign conventions before placing values.",
  },
  {
    id: "p_optics_02",
    title: "Mirror Formula",
    formula: "\\frac{1}{f} = \\frac{1}{v} + \\frac{1}{u}",
    category: "Optics",
    subject: "Physics",
    chapter: "Light - Reflection and Refraction",
    description: "Relates the focal length to image and object distance for a spherical mirror.",
    variables: [{ symbol: "f", meaning: "Focal Length" }, { symbol: "v", meaning: "Image Distance" }, { symbol: "u", meaning: "Object Distance" }],
    targetClasses: [10, 12],
    importanceTags: ["🎯 Board Exam Focused"],
  },

  // ================= Chemistry (Classes 9-12) =================
  {
    id: "c_mole_01",
    title: "Number of Moles",
    formula: "n = \\frac{m}{M}",
    category: "Physical Chemistry",
    subject: "Chemistry",
    chapter: "Some Basic Concepts of Chemistry",
    description: "Calculates the number of moles from given mass and molar mass.",
    variables: [{ symbol: "n", meaning: "Moles", unit: "mol" }, { symbol: "m", meaning: "Given Mass", unit: "g" }, { symbol: "M", meaning: "Molar Mass", unit: "g/mol" }],
    targetClasses: [9, 11, 12],
    importanceTags: ["🔥 Most Important"],
    commonMistakes: "Using mass in kg instead of grams.",
  },
  {
    id: "c_sol_01",
    title: "Molarity",
    formula: "M = \\frac{n}{V}",
    category: "Solutions",
    subject: "Chemistry",
    chapter: "Solutions",
    description: "The concentration of a solute in a solution, expressed as moles per liter.",
    variables: [{ symbol: "n", meaning: "Moles of solute", unit: "mol" }, { symbol: "V", meaning: "Volume of solution", unit: "L" }],
    targetClasses: [11, 12],
    importanceTags: ["⭐ Frequently Asked"],
    commonMistakes: "Using volume of solvent instead of volume of entire solution.",
    examTip: "Volume must always be in Liters. If given in mL, divide by 1000.",
  },
  {
    id: "c_kin_01",
    title: "First Order Reaction Half-Life",
    formula: "t_{1/2} = \\frac{0.693}{k}",
    category: "Chemical Kinetics",
    subject: "Chemistry",
    chapter: "Chemical Kinetics",
    description: "The time required for a reactant to reach half of its initial concentration in a first-order reaction.",
    variables: [{ symbol: "t_{1/2}", meaning: "Half-life", unit: "s" }, { symbol: "k", meaning: "Rate constant", unit: "s^{-1}" }],
    targetClasses: [12],
    importanceTags: ["🎯 Board Exam Focused"],
    commonMistakes: "Applying this formula to zero-order or second-order reactions.",
  },
  {
    id: "c_eq_01",
    title: "pH Formula",
    formula: "pH = -\\log_{10}[H^+]",
    category: "Physical Chemistry",
    subject: "Chemistry",
    chapter: "Equilibrium",
    description: "Measures the acidity or basicity of an aqueous solution.",
    variables: [{ symbol: "[H^+]", meaning: "Concentration of Hydrogen ions", unit: "mol/L" }],
    targetClasses: [11, 12],
    importanceTags: ["📘 NCERT Essential"],
    commonMistakes: "Forgetting the negative sign in the calculation.",
  }
];
